Lint/IneffectiveAccessModifier:
  Exclude:
    - 'lib/mongoid_enumerable.rb'

Lint/UnusedMethodArgument:
  Exclude:
    - 'lib/mongoid_enumerable.rb'

Metrics/MethodLength:
  Max: 16

Metrics/ParameterLists:
  Max: 7

Layout/LineLength:
  Max: 135
