Lint/IneffectiveAccessModifier:
  Exclude:
    - 'lib/mongoid_enumerable.rb'

Lint/UnusedMethodArgument:
  Exclude:
    - 'lib/mongoid_enumerable.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 16

Metrics/ParameterLists:
  Max: 7

Style/ExpandPathArguments:
  Exclude:
    - 'mongoid_enumerable.gemspec'

Layout/LineLength:
  Max: 135
